### ISSUE TITLE
Create new file cancelled when click away from the 

### ISSUE THREAD

**Issue by Maunique** [unchartedsoftware/PLUTO#233] opened 2017-12-08 20:22 UTC
Click Add a new file to process

Add details and then click off the pop-up.

The pop-up window disappears and the create is cancelled. This doesn't seem right.

**Comment by Maunique** [comment] 2017-12-08 20:54
Clone is also cancelled when click away.

**Comment by lcorrigall** [comment] 2018-01-17 18:16
Duplicate of #305

**Closed by lcorrigall** 2018-01-17 18:16 UTC
Labels: enhancement
