### ISSUE TITLE
Validation configuration changes do not save after an upload

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#551] opened 2018-05-04 18:16 UTC
Pluto ver 1.0.10

Steps to reproduce:
1) Open a validation
2) Click "Upload" (doesn't matter if it fails or succeeds)
3) Change a validation rule property
4) Click "Save"
    -> A popup will appear denoting the changes were saved and the UI will reload
    -> Review the property changed in step 3 and it shows the old value.

**Comment by pandersen-uncharted** [comment] 2018-05-23 13:40
I can't reproduce this and believe it was fixed with the fix to #549.

**Closed** 2018-06-08 17:19 UTC
Labels: bug
