### ISSUE TITLE
parser state is not passed to PythonCSVRule custom rule

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#554] opened 2018-05-15 20:56 UTC
Pluto version 1.0.10

We are currently creating a custom python validation rule based off of PythonCSVRule.  When the validation is run the error "No parser state supplied to PythonCSVRule" is output.  If the ruleset has another validation rule before our PythonCSVRule that does properly set the state the error does not appear.  Setting the requiredParser property on our rule does not set the state either.  

Can you please advise how to properly set the parser state or patch the code if it is a code issue?  Thanks.

**Comment by pandersen-uncharted** [comment] 2018-05-22 16:41
I can't reproduce this. What I'd suggest is taking the existing test_config/customRules/validateColumnRegEx.py file (and the related JSON) and replacing your problem script with this one (renamed to the name of your script) and seeing if the problem still occurs.

Looking at the code I can see no reason why your code should not be getting the parser state.

**Comment by pandersen-uncharted** [comment] 2018-05-22 17:56
Try a ruleset with no rules. And try a file with Japanese characters in the headers.

**Comment by pandersen-uncharted** [comment] 2018-05-23 13:11
ParserAPI.js at line 20 sets the sharedData.Parser which eventually gets used as the parserState in RunExternalProcess. This fails to happen if there is no config.__state nor config.__state.sharedData.

**Comment by pandersen-uncharted** [comment] 2018-05-23 13:19
config.__state and config.__state.sharedData are always set in the validator (in runRules()). So I can't see how sharedData.Parser would not be set in ParserAPI.js.

**Comment by pandersen-uncharted** [comment] 2018-05-23 17:34
From Luke:

> That parser config gets added by the CSV parser rule -- there was a bug before where if the config didn't have a JS csv rule, then the parser wouldn't add it's info to the config.  That was fixed, but I did make some big changes to the final rules array builder.  There should be some tests though to make sure that it's still working.

So it sounds like this may be fixed in the current version.

**Comment by bb-acarrera** [comment] 2018-05-29 17:35
This issue still appears in 1.0.11

**Comment by bb-acarrera** [comment] 2018-06-01 12:42
This issue still appears in version 1.0.12

**Comment by bb-acarrera** [comment] 2018-06-04 20:51
In order to solve this issue the `"parser": "CSVParser"` needs to be added to the plugin json config.  After adding that the error disappears.

**Closed** 2018-06-08 17:18 UTC
Labels: bug
